#!/bin/sh

trap exit ERR

DIR=ffmpeg-armv6
CONFIGURE_OPTIONS="--enable-gpl --enable-postproc --enable-swscale --enable-avfilter"

svn co -r22403 svn://svn.ffmpeg.org/ffmpeg/trunk $DIR

cd $DIR
mkdir -p dist

./configure --cc=/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/gcc-4.2 --as='gas-preprocessor.pl /Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/gcc-4.2' --sysroot=/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS3.0.sdk --prefix="dist" --enable-cross-compile --target-os=darwin --arch=arm --cpu=arm1176jzf-s --extra-cflags='-arch armv6' --extra-ldflags='-arch armv6' $CONFIGURE_OPTIONS

make && make install

echo "Installed: $DIR/dist"
