#!/bin/sh

trap exit ERR

FFMPEG_DIR=ffmpeg-armv6
SCRIPT_DIR=$( (cd -P $(dirname $0) && pwd) )

svn co -r22403 svn://svn.ffmpeg.org/ffmpeg/trunk $FFMPEG_DIR

cd $FFMPEG_DIR
mkdir -p dist

# Default configure options
CONFIGURE_OPTIONS="--enable-gpl --enable-postproc --enable-swscale --enable-avfilter"

# Add x264 if we built that
X264_DIST="$SCRIPT_DIR/x264-armv6/dist"
if [ -d "$X264_DIST" ]; then
  CONFIGURE_OPTIONS="$CONFIGURE_OPTIONS --enable-libx264 --extra-ldflags=-L$X264_DIST/lib --extra-cflags=-I$X264_DIST/include"
fi

echo "Configure options: $CONFIGURE_OPTIONS"

./configure --cc=/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/gcc-4.2 --as='gas-preprocessor.pl /Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/gcc-4.2' --sysroot=/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS3.0.sdk --prefix="dist" --enable-cross-compile --target-os=darwin --arch=arm --cpu=arm1176jzf-s --extra-cflags='-arch armv6' --extra-ldflags='-arch armv6' $CONFIGURE_OPTIONS

make && make install

echo "Installed: $FFMPEG_DIR/dist"
