#!/bin/sh

trap exit ERR

DIR=xvidcore
SCRIPT_DIR=$( (cd -P $(dirname $0) && pwd) )
DIST_DIR="$SCRIPT_DIR/xvid-armv7"

cd $SCRIPT_DIR/$DIR
mkdir -p $DIST_DIR

cd build/generic/

FLAGS="-arch armv7 -isysroot /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS3.0.sdk"

CC=/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/gcc-4.2 LDFLAGS=$FLAGS CFLAGS=$FLAGS ./configure --host=arm-apple-darwin --prefix="$DIST_DIR" --enable-pic

make && make install

echo "Installed: $DIST_DIR"
