#!/bin/sh

trap exit ERR

ARCHS="armv6 armv7 i386"

BUILD_LIBS="libxvidcore.a"

OUTPUT_DIR="xvid-uarch"
mkdir -p $OUTPUT_DIR/lib
mkdir -p $OUTPUT_DIR/include

for LIB in $BUILD_LIBS; do 
  LIPO_CREATE=""
  for ARCH in $ARCHS; do
    LIPO_CREATE="$LIPO_CREATE-arch $ARCH xvid-$ARCH/lib/$LIB "
  done
  OUTPUT="$OUTPUT_DIR/lib/$LIB"
  echo "Creating: $OUTPUT"
  lipo -create $LIPO_CREATE -output $OUTPUT
  lipo -info $OUTPUT
done

echo "Copying headers from xvid-i386..."
cp -R xvid-i386/include/* $OUTPUT_DIR/include

